update pyproject.toml
`project.license` is deprecated
https://raw.githubusercontent.com/tombi-toml/tombi/refs/tags/v0.9.3/www.schemastore.org/pyproject.json

`tool.setuptools_scm.write_to = "src/ufoLib2/_version.py"` is deprecated
https://www.schemastore.org/partial-setuptools-scm.json

`tool.pytest.ini_options` is deprecated
https://www.schemastore.org/partial-pytest.json

addopts: Expected a value of type Array, but found String

SetuptoolsDeprecationWarning: 'tool.setuptools.license-files' is deprecated in favor of 'project.license-files'

setuptools.errors.InvalidConfigError: License classifiers have been superseded by license expressions (see https://peps.python.org/pep-0639/). Please remove:

      License :: OSI Approved :: Apache Software License

formatted with https://tombi-toml.github.io/tombi/

README: MD034/no-bare-urls: Bare URL used